Indexer development
Yeti-Robotics/clone-offseason-2024 pull request #12
Opened 2024-06-27 22:26 UTC by adarsh-cms

2024-06-27 22:34 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/IndexSubsystem.java
> +    }
Why do we need both functions here? Both accomplish similar things.

2024-06-27 22:36 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/IndexSubsystem.java
> +    private final static IndexSubsystem INSTANCE = null;
This is never used

2024-06-27 22:37 UTC, drew-beamer reviewed
See comment

2024-06-27 22:44 UTC, samperlmutter requested changes

2024-06-27 22:44 UTC, samperlmutter commented on src/main/java/frc/robot/subsystems/IndexSubsystem.java
> +    }
This method doesn't actually set the state, it gets the state then sets the `indexMotor` speed accordingly. These can also be consolidated into methods on the enum

2024-06-27 22:44 UTC, samperlmutter commented on src/main/java/frc/robot/subsystems/IndexSubsystem.java
> +    }
We shouldn't be basing whether we have the note on the value in smart dashboard. smart dashboard should only represent the state after the fact.

2024-07-02 23:40 UTC, samperlmutter approved these changes

2024-07-02 23:41 UTC, merged